language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"

matrix:
   allow_failures:
      - perl: "5.8"

branches:
    except:
        - "release/cpan"

before_install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'

   # gotta love failing pod tests blowing everything up...
   - cpanm -q TAP::Harness::Restricted || { cat ~/.cpanm/build.log ; false ; }
   - export HARNESS_SUBCLASS=TAP::Harness::Restricted

   # Moose installs in parallel quite nicely.
   - HARNESS_OPTIONS=j8:c cpanm -q Moose       || { cat ~/.cpanm/build.log ; false ; }
   #- HARNESS_OPTIONS=j8:c cpanm -q Dist::Zilla || { cat ~/.cpanm/build.log ; false ; }

   # for DZP LinkCheck
   - cpanm --skip-satisfied -q CPANPLUS || { cat ~/.cpanm/build.log ; false ; }
   - cpanp x

install:
   # not so much install our package as all its prereqs
   #- dzil authordeps --missing        | cpanm -q || { cat ~/.cpanm/build.log ; false ; }
   #- dzil listdeps --author --missing | cpanm -q || { cat ~/.cpanm/build.log ; false ; }
   - cpanm --installdeps .

script:
   - export DZSIGN=archive
   - unset HARNESS_SUBCLASS
   #- dzil test --release --author
   - prove -lr t/
